version: "3.1"

services:
  ts_mysql_db:
    image: mysql:5.7
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: ts_mysql_db
      MYSQL_ROOT_USER: ts_node
      MYSQL_USER: ts_node
      MYSQL_ROOT_PASSWORD: secret1234
      MYSQL_PASSWORD: secret1234

# docker se lleva mal con los -, reemplaze por _ y funciono.